version: "2.1"
services:
  oryx:
    image: hub.vpclub.cn/ossrs/oryx:5-rc1
    restart: always
    container_name: oryx
    ports:
      - 80:2022
      - 443:2443
      - 1935:1935
      - 8000:8000/udp
      - 10080:10080/udp
    environment:
      DATASOURCE_TYPE: mysql
      MYSQL_URL: root:qweQWEASD123@tcp(mariadb:3306)/oryx?charset=utf8mb4&parseTime=True&loc=Local
#      DATASOURCE_TYPE: redis
#      REDIS_DATABASE: 0
#      REDIS_HOST: localhost
#      REDIS_PORT: 3306
#      REDIS_PASSWORD: xxx
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: qweQWEASD123
      MYSQL_USER: demo
      MYSQL_PASSWORD: qweQWEASD123
      MYSQL_DATABASE: oryx
    ports:
      - "3306:3306"